### ISSUE TITLE
New installation doesn't update database with installation key and authentication URL

### ISSUE THREAD

**Issue by rini21** [Cafe-Variome/CafeVariome#1]
## Description
Upon cloning the repository and installing using the `composer CVInstall` command, going to the base URL returns an error banner (as below):
![image](https://user-images.githubusercontent.com/24955128/189659323-86547986-9981-4af4-9e82-57f2b3be313d.png)

## Remediation
Rectified by updating the System Settings with the installation key and authentication server URL. 

## Steps to reproduce
- Clone this repository
- Edit env template to .env with Base URL and Database values
- `composer install`
- `composer CVInstall`, then add the obtained installation key and authentication URL in the CLI installer
- Go to the Base URL

## Other Information 
Environment running on Linux Ubuntu 20.04.4 LTS with PHP Version 8.0.22, with Apache/2.4.41 webserver. 

## TODO
- [x] Check Install/CVInstaller.php and verify that the DB update query is functioning as expected.

**Comment by aryaei2000** [comment]
This is fixed as the SQL queries in the CVInstaller.php were not up to date with the latest schema of the settings table. See https://github.com/Cafe-Variome/CafeVariome/commit/10cd2bd7f7fd75f436fba081c10c4f78d7488416

**Comment by rini21** [comment]
### This issue persists even after the most recent update (version 2.3.0). It was tested on lamps and local dev.

**Comment by rini21** [comment]
https://github.com/Cafe-Variome/CafeVariome/commit/c89670d456e5ad7c0b56cf9977b367347b95ac90 fixed this issue.
