### ISSUE TITLE
Discovery Attributtes 

### ISSUE THREAD

**Issue by rini21** [Cafe-Variome/CafeVariome#3]
## Description 
After a successful installation, the query interface element to select the **Patient Characteristics** shows a 'No results found' in the dropdown. The following checks were made to check in multiple installations, and the issue persists: 
- All the services are running (viz., Elasticsearch, Neo4J, Service and Authenticator).
- Indices for Elasticsearch and User Interface are successfully created.
- Source has been assigned to relevant discovery groups.

![image](https://user-images.githubusercontent.com/24955128/190204143-b9f00726-519e-48ec-a48c-66abc6d4f1b4.png)

Upon further troubleshooting, `/AjaxApi/GetPhenotypeAttributes/(network_key)` returns a success 200 status code, but the attribute_values are not being populated as below: 
![image](https://user-images.githubusercontent.com/24955128/190204935-5a15dea2-a4a6-447d-9a01-762cc64f8912.png)

## Steps to reproduce the issue
- Install Cafe Variome
- Create/join a Network
- Create Discovery Groups
- Create Source
- Import/Upload Data
- Generate indices (ES, UI)
- Head to the Discover page
## TODO
- [ ] Inspect `resources/js/cafevariome/query_builder.js`

**Comment by aryaei2000** [comment]
This is fixed now as of https://github.com/Cafe-Variome/CafeVariome/commit/c2b73d5f881f6bf9ca265da7ed2734c4cea42a46.

**Comment by rini21** [comment]
Attributes are still not being generated even after the latest and most recent updates and regenerating UI index. The following error is logged:
![image](https://user-images.githubusercontent.com/24955128/191303104-5b8cc784-163c-4e5b-8aaf-e9ecf2af4271.png)

**Comment by rini21** [comment]
Review #4 and merge it @aryaei2000
